web:
  image: tutorial/apache
  ports:
    - "8080:80"
    - "9000"
  volumes:
#!!!set necessary DocumentRoot in ./images/cfg/apache_vhost.conf
    - ./src/www:/var/www
#set cfg
    - ./images/cfg/apache_vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    - ./images/cfg/xdebug.ini:/etc/php5/apache2/conf.d/99_xdebug.ini
    - ./images/cfg/.selected_editor:/root/.selected_editor
#set prog and data
    - ./src/prg:/opt/prg
    - ./src/data:/opt/data
#logs
    - ./src/logs/apache2:/var/log/apache2
  
